-- AlterTable
ALTER TABLE "CrossingVideo" ADD COLUMN     "sourceType" TEXT NOT NULL DEFAULT 'FILE',
ADD COLUMN     "sourceUrl" TEXT,
ALTER COLUMN "filename" DROP NOT NULL,
ALTER COLUMN "originalName" DROP NOT NULL,
ALTER COLUMN "mimetype" DROP NOT NULL,
ALTER COLUMN "size" DROP NOT NULL,
ALTER COLUMN "path" DROP NOT NULL;
